In [14]:
import pandas as pd
from glob import glob
import os
import json

In [ ]:
dfs = []
for json_path in glob('./logs/finetune_cpb_20250814/*/*/*/*/*/*/*.json'):
    
    path_parts = json_path.split('/')
    method = path_parts[-5]
    n_train = int(path_parts[-4].split('_')[-1])
    rep = int(path_parts[-3].split('_')[-1])
    fold = int(path_parts[-2].split('_')[-1])
    
    # print(f'Processing {method} rep {rep} fold {fold} with {n_train} training samples')
    metrics_data = json.load(open(json_path, 'r'))
    metrics_data['method'] = method
    metrics_data['n_train'] = n_train
    metrics_data['rep'] = rep
    metrics_data['fold'] = fold
    dfs.append(pd.DataFrame(metrics_data, index=[0]))

metrics_df = pd.concat(dfs, ignore_index=True)
display(metrics_df)

Processing srs rep 2 fold 4 with 500 training samples
Processing srs rep 2 fold 3 with 500 training samples
Processing srs rep 2 fold 2 with 500 training samples
Processing srs rep 2 fold 1 with 500 training samples
Processing srs rep 3 fold 4 with 500 training samples
Processing srs rep 3 fold 3 with 500 training samples
Processing srs rep 3 fold 2 with 500 training samples
Processing srs rep 3 fold 1 with 500 training samples
Processing srs rep 1 fold 4 with 500 training samples
Processing srs rep 1 fold 3 with 500 training samples
Processing srs rep 1 fold 2 with 500 training samples
Processing srs rep 1 fold 1 with 500 training samples
Processing srs rep 0 fold 4 with 500 training samples
Processing srs rep 0 fold 3 with 500 training samples
Processing srs rep 0 fold 2 with 500 training samples
Processing srs rep 0 fold 1 with 500 training samples
Processing srs rep 2 fold 4 with 750 training samples
Processing srs rep 2 fold 3 with 750 training samples
Processing srs rep 2 fold 2 with 750 training samples
Processing srs rep 2 fold 1 with 750 training samples
Processing srs rep 3 fold 4 with 750 training samples
Processing srs rep 3 fold 3 with 750 training samples
Processing srs rep 3 fold 2 with 750 training samples
Processing srs rep 3 fold 1 with 750 training samples
Processing srs rep 1 fold 4 with 750 training samples
Processing srs rep 1 fold 3 with 750 training samples
Processing srs rep 1 fold 2 with 750 training samples
Processing srs rep 1 fold 1 with 750 training samples
Processing srs rep 0 fold 4 with 750 training samples
Processing srs rep 0 fold 3 with 750 training samples
Processing srs rep 0 fold 2 with 750 training samples
Processing srs rep 0 fold 1 with 750 training samples
Processing srs rep 2 fold 4 with 250 training samples
Processing srs rep 2 fold 3 with 250 training samples
Processing srs rep 2 fold 2 with 250 training samples
Processing srs rep 2 fold 1 with 250 training samples
Processing srs rep 3 fold 4 with 250 training samples
Processing srs rep 3 fold 3 with 250 training samples
Processing srs rep 3 fold 2 with 250 training samples
Processing srs rep 3 fold 1 with 250 training samples
Processing srs rep 1 fold 4 with 250 training samples
Processing srs rep 1 fold 3 with 250 training samples
Processing srs rep 1 fold 2 with 250 training samples
Processing srs rep 1 fold 1 with 250 training samples
Processing srs rep 0 fold 4 with 250 training samples
Processing srs rep 0 fold 3 with 250 training samples
Processing srs rep 0 fold 2 with 250 training samples
Processing srs rep 0 fold 1 with 250 training samples
Processing sss rep 2 fold 4 with 500 training samples
Processing sss rep 2 fold 3 with 500 training samples
Processing sss rep 2 fold 2 with 500 training samples
Processing sss rep 2 fold 1 with 500 training samples
Processing sss rep 3 fold 4 with 500 training samples
Processing sss rep 3 fold 3 with 500 training samples
Processing sss rep 3 fold 2 with 500 training samples
Processing sss rep 3 fold 1 with 500 training samples
Processing sss rep 4 fold 2 with 500 training samples
Processing sss rep 4 fold 1 with 500 training samples
Processing sss rep 1 fold 4 with 500 training samples
Processing sss rep 1 fold 3 with 500 training samples
Processing sss rep 1 fold 2 with 500 training samples
Processing sss rep 1 fold 1 with 500 training samples
Processing sss rep 0 fold 4 with 500 training samples
Processing sss rep 0 fold 3 with 500 training samples
Processing sss rep 0 fold 2 with 500 training samples
Processing sss rep 0 fold 1 with 500 training samples
Processing sss rep 2 fold 4 with 750 training samples
Processing sss rep 2 fold 3 with 750 training samples
Processing sss rep 2 fold 2 with 750 training samples
Processing sss rep 2 fold 1 with 750 training samples
Processing sss rep 3 fold 4 with 750 training samples
Processing sss rep 3 fold 3 with 750 training samples
Processing sss rep 3 fold 2 with 750 training samples
Processing sss rep 3 fold 1 with 750 training samples
Processing sss rep 1 fold 4 with 750 training samples
Processing sss rep 1 fold 3 with 750 training samples
Processing sss rep 1 fold 2 with 750 training samples
Processing sss rep 1 fold 1 with 750 training samples
Processing sss rep 0 fold 4 with 750 training samples
Processing sss rep 0 fold 3 with 750 training samples
Processing sss rep 0 fold 2 with 750 training samples
Processing sss rep 0 fold 1 with 750 training samples
Processing sss rep 2 fold 4 with 250 training samples
Processing sss rep 2 fold 3 with 250 training samples
Processing sss rep 2 fold 2 with 250 training samples
Processing sss rep 2 fold 1 with 250 training samples
Processing sss rep 3 fold 4 with 250 training samples
Processing sss rep 3 fold 3 with 250 training samples
Processing sss rep 3 fold 2 with 250 training samples
Processing sss rep 3 fold 1 with 250 training samples
Processing sss rep 4 fold 3 with 250 training samples
Processing sss rep 1 fold 4 with 250 training samples
Processing sss rep 1 fold 3 with 250 training samples
Processing sss rep 1 fold 2 with 250 training samples
Processing sss rep 1 fold 1 with 250 training samples
Processing sss rep 0 fold 4 with 250 training samples
Processing sss rep 0 fold 3 with 250 training samples
Processing sss rep 0 fold 2 with 250 training samples
Processing sss rep 0 fold 1 with 250 training samples
Processing semss rep 2 fold 4 with 500 training samples
Processing semss rep 2 fold 3 with 500 training samples
Processing semss rep 2 fold 2 with 500 training samples
Processing semss rep 2 fold 1 with 500 training samples
Processing semss rep 3 fold 4 with 500 training samples
Processing semss rep 3 fold 3 with 500 training samples
Processing semss rep 3 fold 2 with 500 training samples
Processing semss rep 3 fold 1 with 500 training samples
Processing semss rep 1 fold 4 with 500 training samples
Processing semss rep 1 fold 3 with 500 training samples
Processing semss rep 1 fold 2 with 500 training samples
Processing semss rep 1 fold 1 with 500 training samples
Processing semss rep 0 fold 4 with 500 training samples
Processing semss rep 0 fold 3 with 500 training samples
Processing semss rep 0 fold 2 with 500 training samples
Processing semss rep 0 fold 1 with 500 training samples
Processing semss rep 2 fold 4 with 750 training samples
Processing semss rep 2 fold 3 with 750 training samples
Processing semss rep 2 fold 2 with 750 training samples
Processing semss rep 2 fold 1 with 750 training samples
Processing semss rep 3 fold 4 with 750 training samples
Processing semss rep 3 fold 3 with 750 training samples
Processing semss rep 3 fold 2 with 750 training samples
Processing semss rep 3 fold 1 with 750 training samples
Processing semss rep 1 fold 4 with 750 training samples
Processing semss rep 1 fold 3 with 750 training samples
Processing semss rep 1 fold 2 with 750 training samples
Processing semss rep 1 fold 1 with 750 training samples
Processing semss rep 0 fold 4 with 750 training samples
Processing semss rep 0 fold 3 with 750 training samples
Processing semss rep 0 fold 2 with 750 training samples
Processing semss rep 0 fold 1 with 750 training samples
Processing semss rep 2 fold 4 with 250 training samples
Processing semss rep 2 fold 3 with 250 training samples
Processing semss rep 2 fold 2 with 250 training samples
Processing semss rep 2 fold 1 with 250 training samples
Processing semss rep 3 fold 4 with 250 training samples
Processing semss rep 3 fold 3 with 250 training samples
Processing semss rep 3 fold 2 with 250 training samples
Processing semss rep 3 fold 1 with 250 training samples
Processing semss rep 1 fold 4 with 250 training samples
Processing semss rep 1 fold 3 with 250 training samples
Processing semss rep 1 fold 2 with 250 training samples
Processing semss rep 1 fold 1 with 250 training samples
Processing semss rep 0 fold 4 with 250 training samples
Processing semss rep 0 fold 3 with 250 training samples
Processing semss rep 0 fold 2 with 250 training samples
Processing semss rep 0 fold 1 with 250 training samples

,accuracy,f1_score,precision,recall,jaccard,kappa,macro_f1_score,macro_precision,macro_recall,macro_jaccard,weighted_f1_score,weighted_precision,weighted_recall,weighted_jaccard,method,n_train,rep,fold
0,0.866605,0.861296,0.861147,0.866605,0.772750,0.919744,0.649709,0.749110,0.619039,0.524582,0.861296,0.861147,0.866605,0.772750,srs,500,2,4
1,0.865999,0.863784,0.865266,0.865999,0.775827,0.918495,0.650537,0.742499,0.622086,0.529494,0.863784,0.865266,0.865999,0.775827,srs,500,2,3
2,0.870716,0.867029,0.866969,0.870716,0.780526,0.921938,0.657757,0.753311,0.620135,0.534788,0.867029,0.866969,0.870716,0.780526,srs,500,2,2
3,0.870978,0.867389,0.866086,0.870978,0.781046,0.922064,0.670144,0.734262,0.639757,0.544337,0.867389,0.866086,0.870978,0.781046,srs,500,2,1
4,0.871395,0.867072,0.866456,0.871395,0.780189,0.922463,0.677873,0.752449,0.652433,0.552909,0.867072,0.866456,0.871395,0.780189,srs,500,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142,0.864827,0.861118,0.861869,0.864827,0.771933,0.918424,0.662334,0.762102,0.625670,0.534578,0.861118,0.861869,0.864827,0.771933,semss,250,1,1
143,0.860148,0.855431,0.854816,0.860148,0.764798,0.915561,0.633723,0.724421,0.608275,0.514123,0.855431,0.854816,0.860148,0.764798,semss,250,0,4
144,0.860638,0.856689,0.855518,0.860638,0.765114,0.916008,0.677099,0.735967,0.643570,0.544589,0.856689,0.855518,0.860638,0.765114,semss,250,0,3
145,0.858543,0.853904,0.853907,0.858543,0.762418,0.914660,0.640875,0.717571,0.611587,0.512371,0.853904,0.853907,0.858543,0.762418,semss,250,0,2
146,0.860187,0.854638,0.854451,0.860187,0.764693,0.915937,0.638136,0.744109,0.605952,0.516086,0.854638,0.854451,0.860187,0.764693,semss,250,0,1

In [21]:
metrics_df.groupby(['method', 'n_train']).mean().sort_values(by='macro_jaccard', ascending=False)

,,accuracy,f1_score,precision,recall,jaccard,kappa,macro_f1_score,macro_precision,macro_recall,macro_jaccard,weighted_f1_score,weighted_precision,weighted_recall,weighted_jaccard,rep,fold
method,n_train,,,,,,,,,,,,,,,,
semss,750,0.873893,0.871387,0.870792,0.873893,0.785391,0.923632,0.703125,0.756294,0.677076,0.573216,0.871387,0.870792,0.873893,0.785391,1.500000,2.500000
srs,750,0.874756,0.871812,0.870869,0.874756,0.786569,0.924308,0.694594,0.744762,0.664746,0.565273,0.871812,0.870869,0.874756,0.786569,1.500000,2.500000
sss,750,0.873038,0.869575,0.868570,0.873038,0.783708,0.923282,0.684850,0.739421,0.658719,0.557608,0.869575,0.868570,0.873038,0.783708,1.500000,2.500000
semss,500,0.869478,0.866583,0.866287,0.869478,0.779040,0.921043,0.685761,0.753324,0.655464,0.557286,0.866583,0.866287,0.869478,0.779040,1.500000,2.500000
sss,500,0.869441,0.865675,0.864640,0.869441,0.778484,0.921165,0.672817,0.735453,0.645577,0.546641,0.865675,0.864640,0.869441,0.778484,1.777778,2.388889
srs,500,0.869412,0.865851,0.864980,0.869412,0.778758,0.921097,0.670195,0.735311,0.641425,0.543726,0.865851,0.864980,0.869412,0.778758,1.500000,2.500000
semss,250,0.859527,0.855340,0.855666,0.859527,0.764463,0.915183,0.645887,0.734810,0.615600,0.520237,0.855340,0.855666,0.859527,0.764463,1.500000,2.500000
sss,250,0.859445,0.854072,0.853144,0.859445,0.763568,0.915391,0.634642,0.718861,0.604734,0.511726,0.854072,0.853144,0.859445,0.763568,1.647059,2.529412
srs,250,0.859859,0.854483,0.853498,0.859859,0.764071,0.915658,0.631759,0.718523,0.599687,0.508754,0.854483,0.853498,0.859859,0.764071,1.500000,2.500000