In [2]:
import os
import geopandas as gpd
import pandas as pd
import numpy as np
from glob import glob
import rasterio as rio
from rasterio.mask import mask
from rasterio.io import MemoryFile
import pickle
import matplotlib.pyplot as plt
from concurrent.futures import ThreadPoolExecutor
from threading import Lock
from src.mslandcover.config import MSTM_PROJ4
from src.mslandcover.utils import raise_if_not_exists
import cv2

In [60]:
# load the shapefilse with boundaries of the regions
shapefiles = glob('data/MS_NAIP_2023/*/*.shp')
gdfs = []
for shapefile in shapefiles:
    gdf = gpd.read_file(shapefile).to_crs(MSTM_PROJ4) # convert to the same projection
    raster_path = glob(os.path.join(os.path.dirname(shapefile), '*_1m.tif'))[0]
    gdf['raster_path'] = raster_path
    gdfs.append(gdf)

raster_boundaries_gdf = gpd.GeoDataFrame(pd.concat(gdfs))[['raster_path', 'geometry']] # only keep the relevant columns
raster_boundaries_gdf = raster_boundaries_gdf.dissolve(by='raster_path').reset_index() # dissolve the geometries to get the boundaries of the raster
raster_boundaries_gdf.to_file('data/regions_boundaries.gpkg', driver='GPKG')

In [40]:
# load the samples parquet
samples = gpd.read_parquet('./data/sampling/samples.par')

# spatial join with the raster boundaries
raster_boundaries_gdf['raster_geometry'] = raster_boundaries_gdf['geometry'] # make a copy of the geometry
samples = gpd.sjoin(samples, raster_boundaries_gdf, predicate='intersects', how='left')
samples['intersection_area'] = samples.apply(lambda x: x['geometry'].intersection(x['raster_geometry']).area, axis=1)

In [ ]:
def extract_mask(sample, raster_dataset):
    
    out_image, out_transform = mask(raster_dataset, [sample['geometry']], crop=True, all_touched=True)
    out_meta = raster_dataset.meta.copy()

    if out_image.shape[1] > 256 or out_image.shape[2] > 256:
        # crop the image to 256x256
        out_image = out_image[:, :256, :256]

    filename = str(sample.name)
    if out_image.shape != (3, 256, 256):\
        return
    
    nd_values = np.array([raster_dataset.nodata] * 3)
    pixels_with_nd = np.equal(out_image.transpose(1, 2, 0).reshape(-1, 3), nd_values).all(axis=1)
    if pixels_with_nd.any():
        
        if pixels_with_nd.sum() > 0.05 * len(pixels_with_nd):
            return
    
    out_meta.update({
        "driver": "GTiff",
        "height": out_image.shape[1],
        "width": out_image.shape[2],
        "transform": out_transform,
    })
    
    out_path = os.path.join('data', 'splits', sample['split'], 'input', filename + '.tif')
    with rio.open(out_path, 'w', **out_meta) as dst:
        dst.write(out_image)
    
    if sample['split'] == 'pretrain' or sample['split'] == 'pretrain_val': # save HSV image for pretraining
        hsv_image = cv2.cvtColor(out_image.transpose(1, 2, 0), cv2.COLOR_RGB2HSV).transpose(2, 0, 1)
        
        target_path = os.path.join('data', 'splits', sample['split'], 'target', filename + '.tif')
        with rio.open(target_path, 'w', **out_meta) as dst:
            dst.write(hsv_image)

def extract_raster(samples_group):
    
    raster_path = samples_group[0]
    with MemoryFile(open(raster_path, 'rb')) as memfile:
        with rio.open(memfile) as raster_dataset:
            samples_group[1].apply(lambda x: extract_mask(x, raster_dataset), axis=1)

# sub_samples = samples[samples['split'].isin(['train', 'test', 'val'])]
n_threads = 4
with ThreadPoolExecutor(max_workers=n_threads) as executor:
    list(executor.map(extract_raster, list(samples.groupby('raster_path'))))

In [ ]:
# check which images did not get sampled - these most likely have pathces in 
# multiple rasters which need to be handled separately
sampled_files = [int(os.path.basename(file).replace('.tif', '')) for file in glob('data/splits/*/*/*.tif')]

Index([1590368,  631402,  631402,  451144, 1751567, 1751567, 1966146, 1633483,
       1633483, 1633483,
       ...
       1992753, 1897841, 2407332, 2267476, 1524028, 1524028, 1524028,  624760,
       2033673, 2068866],
      dtype='int64', length=1373)
0

Empty GeoDataFrame
Columns: [geometry, hist_vector, hist_vector_scaled, hist_vector_pca, cluster, split, index_right, raster_path, raster_geometry, intersection_area]
Index: []

In [51]:
def combine_images(gdf):
    print(gdf)


buffered_raster_footprints = raster_boundaries_gdf.copy()
buffered_raster_footprints['geometry'] = buffered_raster_footprints['geometry'].buffer(100)

remaining_samples = gpd.sjoin(remaining_samples.drop(['index_right'], axis=1), buffered_raster_footprints, predicate='intersects', how='left')
display(remaining_samples)

,geometry,hist_vector,hist_vector_scaled,hist_vector_pca,cluster,split,raster_path_left,raster_geometry_left,intersection_area,index_right,raster_path_right,raster_geometry_right
631402,"POLYGON ((395614.025 1480093.786, 395870.025 1...","[0.20833333333333334, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.20833333333333334, 0.0, 0.0, -0.33333333333...","[-1.461855507383653, 2.5955461354892018]",0,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1...",65536.0,5,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1..."
631402,"POLYGON ((395614.025 1480093.786, 395870.025 1...","[0.20833333333333334, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.20833333333333334, 0.0, 0.0, -0.33333333333...","[-1.461855507383653, 2.5955461354892018]",0,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1...",65536.0,13,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1..."
631402,"POLYGON ((395614.025 1480093.786, 395870.025 1...","[0.20833333333333334, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.20833333333333334, 0.0, 0.0, -0.33333333333...","[-1.461855507383653, 2.5955461354892018]",0,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1...",65536.0,5,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1..."
631402,"POLYGON ((395614.025 1480093.786, 395870.025 1...","[0.20833333333333334, 0.0, 0.0, 0.0, 0.0, 0.0,...","[0.20833333333333334, 0.0, 0.0, -0.33333333333...","[-1.461855507383653, 2.5955461354892018]",0,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1...",65536.0,13,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1..."
1145780,"POLYGON ((458590.025 1415069.786, 458846.025 1...","[0.13580246913580246, 0.7160493827160493, 0.0,...","[0.13580246913580246, 8.285714285714286, 0.0, ...","[7.269467655575128, 1.3904592797537614]",7,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1...",65536.0,41,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1..."
1122883,"POLYGON ((455774.025 1444509.786, 456030.025 1...","[0.28125, 0.171875, 0.0, 0.0, 0.0, 0.0, 0.1875...","[0.28125, 1.9888392857142858, 0.0, -0.33333333...","[0.8910178578788672, 1.0867089845273188]",11,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1...",65536.0,41,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1..."
1122883,"POLYGON ((455774.025 1444509.786, 456030.025 1...","[0.28125, 0.171875, 0.0, 0.0, 0.0, 0.0, 0.1875...","[0.28125, 1.9888392857142858, 0.0, -0.33333333...","[0.8910178578788672, 1.0867089845273188]",11,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1...",65536.0,67,data/MS_NAIP_2023\ortho_1-1_hc_s_ms135_2023_1\...,"POLYGON ((441474.074 1431469.137, 441410.122 1..."
1122883,"POLYGON ((455774.025 1444509.786, 456030.025 1...","[0.28125, 0.171875, 0.0, 0.0, 0.0, 0.0, 0.1875...","[0.28125, 1.9888392857142858, 0.0, -0.33333333...","[0.8910178578788672, 1.0867089845273188]",11,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms135_2023_1\...,"POLYGON ((441474.074 1431469.137, 441410.122 1...",65536.0,41,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1..."
1122883,"POLYGON ((455774.025 1444509.786, 456030.025 1...","[0.28125, 0.171875, 0.0, 0.0, 0.0, 0.0, 0.1875...","[0.28125, 1.9888392857142858, 0.0, -0.33333333...","[0.8910178578788672, 1.0867089845273188]",11,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms135_2023_1\...,"POLYGON ((441474.074 1431469.137, 441410.122 1...",65536.0,67,data/MS_NAIP_2023\ortho_1-1_hc_s_ms135_2023_1\...,"POLYGON ((441474.074 1431469.137, 441410.122 1..."
1390568,"POLYGON ((488542.025 1421213.786, 488798.025 1...","[0.0, 0.2345679012345679, 0.0, 0.7160493827160...","[0.0, 2.7142857142857144, 0.0, 0.6213991769547...","[1.9179533810562646, -0.41466434062032015]",14,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms015_2023_1\...,"POLYGON ((464563.644 1382732.659, 464477.012 1...",65536.0,7,data/MS_NAIP_2023\ortho_1-1_hc_s_ms015_2023_1\...,"POLYGON ((464563.644 1382732.659, 464477.012 1..."
1103933,"POLYGON ((453470.025 1413277.786, 453726.025 1...","[0.0, 0.21875, 0.0, 0.0, 0.0, 0.0, 0.1875, 0.5...","[0.0, 2.53125, 0.0, -0.3333333333333333, 0.0, ...","[1.1962402851859457, 2.2009971301903115]",47,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1...",65536.0,41,data/MS_NAIP_2023\ortho_1-1_hc_s_ms083_2023_1\...,"POLYGON ((435312.935 1376057.749, 435249.043 1..."
685812,"POLYGON ((402270.025 1484701.786, 402526.025 1...","[0.25, 0.046875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.70...","[0.25, 0.5424107142857143, 0.0, -0.33333333333...","[-0.8473347033467775, 2.325017370146576]",48,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1...",65536.0,13,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1..."
733955,"POLYGON ((408158.025 1491613.786, 408414.025 1...","[0.0, 0.1111111111111111, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 1.2857142857142858, 0.0, -0.333333333333...","[-0.29936116170594396, 3.2712751566608893]",84,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1...",65536.0,13,data/MS_NAIP_2023\ortho_1-1_hc_s_ms027_2023_1\...,"POLYGON ((384474.683 1473287.396, 384343.835 1..."
785924,"POLYGON ((414558.025 1406877.786, 414814.025 1...","[0.0, 0.75, 0.0, 0.0, 0.0, 0.0, 0.25, 0.0]","[0.0, 8.678571428571429, 0.0, -0.3333333333333...","[7.7672099486858315, 0.8736530752303084]",95,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms133_2023_1\...,"POLYGON ((411308.964 1382867.243, 406818.365 1...",65536.0,66,data/MS_NAIP_2023\ortho_1-1_hc_s_ms133_2023_1\...,"POLYGON ((411308.964 1382867.243, 406818.365 1..."
631311,"POLYGON ((395614.025 1456797.786, 395870.025 1...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.8395061728395...","[0.0, 0.0, 0.0, -0.3333333333333333, 0.0, 0.0,...","[-0.8728331447492095, -0.3587823714904341]",100,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1...",65536.0,5,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1..."
986611,"POLYGON ((439134.025 1369757.786, 439390.025 1...","[0.0, 0.09375, 0.0, 0.0, 0.0, 0.0, 0.609375, 0...","[0.0, 1.0848214285714286, 0.0, -0.333333333333...","[0.06022140813073195, 0.5123061503903829]",170,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms053_2023_1\...,"POLYGON ((411778.113 1341479.23, 411691.994 13...",65536.0,26,data/MS_NAIP_2023\ortho_1-1_hc_s_ms053_2023_1\...,"POLYGON ((411778.113 1341479.23, 411691.994 13..."
986611,"POLYGON ((439134.025 1369757.786, 439390.025 1...","[0.0, 0.09375, 0.0, 0.0, 0.0, 0.0, 0.609375, 0...","[0.0, 1.0848214285714286, 0.0, -0.333333333333...","[0.06022140813073195, 0.5123061503903829]",170,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms053_2023_1\...,"POLYGON ((411778.113 1341479.23, 411691.994 13...",65536.0,25,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1..."
986611,"POLYGON ((439134.025 1369757.786, 439390.025 1...","[0.0, 0.09375, 0.0, 0.0, 0.0, 0.0, 0.609375, 0...","[0.0, 1.0848214285714286, 0.0, -0.333333333333...","[0.06022140813073195, 0.5123061503903829]",170,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1...",65536.0,26,data/MS_NAIP_2023\ortho_1-1_hc_s_ms053_2023_1\...,"POLYGON ((411778.113 1341479.23, 411691.994 13..."
986611,"POLYGON ((439134.025 1369757.786, 439390.025 1...","[0.0, 0.09375, 0.0, 0.0, 0.0, 0.0, 0.609375, 0...","[0.0, 1.0848214285714286, 0.0, -0.333333333333...","[0.06022140813073195, 0.5123061503903829]",170,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1...",65536.0,25,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1..."
1231330,"POLYGON ((469086.025 1358237.786, 469342.025 1...","[0.0, 0.0625, 0.0, 0.0, 0.0, 0.0, 0.9375, 0.0]","[0.0, 0.7232142857142858, 0.0, -0.333333333333...","[-0.014636578811244189, -0.9303802808527629]",210,train,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1...",65536.0,25,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1..."
635372,"POLYGON ((396126.025 1425309.786, 396382.025 1...","[0.027777777777777776, 0.1527777777777778, 0.0...","[0.027777777777777776, 1.767857142857143, 0.0,...","[0.6946274298988053, 0.8424910716729339]",11,val,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1...",65536.0,5,data/MS_NAIP_2023\ortho_1-1_hc_s_ms011_2023_1\...,"POLYGON ((360356.027 1411250.111, 360235.899 1..."
1269023,"POLYGON ((473694.025 1367709.786, 473950.025 1...","[0.0, 0.8194444444444444, 0.0, 0.0138888888888...","[0.0, 9.482142857142858, 0.0, -0.3148148148148...","[8.552963034853468, 1.0571239528984993]",62,val,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1...",65536.0,25,data/MS_NAIP_2023\ortho_1-1_hc_s_ms051_2023_1\...,"POLYGON ((446906.673 1348158.669, 446820.192 1..."

In [9]:
# get footprints of each raster

raster_files = glob('data/MS_NAIP_2023/*/*_1m.tif')
raster_footprints = []
for raster_file in raster_files:
    print(raster_file)
    
    with rio.open(raster_file) as src:
        nodata_mask = src.read_masks(1)
    #     mask = src.read_masks(1)
    #     geoms = list(rio.features.shapes(rio.band(src, 1), mask=mask, transform=src.transform))
    break

data/MS_NAIP_2023\ortho_1-1_hc_s_ms001_2023_1\ortho_1-1_hc_s_ms001_2023_1_1m.tif

<!-- ## Sampling Points for Accuracy Assesment -->

In [67]:
samples['split'].unique()

array(['pretrain', 'pretrain_val', 'train', 'val', 'test'], dtype=object)